name: Dependency Management
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly
  push:
    paths: 
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  audit:
    runs-on: self-hosted    
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}